<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Charleen Ta" />
    
    <link rel="shortcut icon" type="image/x-icon" href="/img/favicon.ico">
    <title>Project 1: Exploratory Data Analysis</title>
    <meta name="generator" content="Hugo 0.79.0" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="/css/main.css" />
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,400,200bold,400old" />
    
    <!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->

    
  </head>

  <body>
    <div id="wrap">
      
      <nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/"><i class="fa fa-home"></i></a>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse" id="navbar">
      <ul class="nav navbar-nav navbar-right">
      
        
        <li><a href="/post/">BLOG</a></li>
        
        <li><a href="/projects/">PROJECTS</a></li>
        
        <li><a href="/resume/">RESUME</a></li>
        
      
      </ul>
    </div>
  </div>
</nav>

      <div class="container">
        <div class="blog-post">
          <h3>
            <strong><a href="/project/project1/">Project 1: Exploratory Data Analysis</a></strong>
          </h3>
        </div>
 
<div class="blog-title">
          <h4>
         January 1, 0001 
            &nbsp;&nbsp;
            
          </h4>
        </div>

        <div class="panel panel-default">
          <div class="panel-body">
            <div class="blogpost">
              


<div id="charleen-ta-ct28558" class="section level2">
<h2>CHARLEEN TA (ct28558)</h2>
</div>
<div id="data-wrangling-and-data-exploration" class="section level2">
<h2>Data Wrangling and Data Exploration</h2>
<div id="instructions" class="section level3">
<h3>Instructions</h3>
<p>A knitted R Markdown document (ideally HTML) and the raw R Markdown file (as .Rmd) should both be submitted to Canvas by 11:59pm on 10/11/2020. These two documents will be graded jointly, so they must be consistent (i.e., don’t change the R Markdown file without also updating the knitted document).</p>
<p>The text of the document should provide a narrative structure around your code/output. All results presented must have corresponding code. Any answers/results/plots etc. given without the corresponding R code that generated the result will not be considered. Furthermore, all code contained in your final project document must work correctly (knit early, knit often)! Please do not include any extraneous code or code which produces error messages. (Code that produces warnings is acceptable, as long as you understand what the warnings mean!)</p>
</div>
<div id="find-data" class="section level3">
<h3>Find data:</h3>
<p>Find two (!) datasets with one variable in common (e.g., dates, times, states, counties, countries, sports players), both with at least 50 observations (i.e., rows) in each. Please think very carefully about whether it makes sense to combine your datasets! If you find one dataset with 50 patients and it has their age, and you find another dataset with 50 <em>different</em> patients that has their ages, it makes no sense to join them based on age (you would just be pairing up random people of the same age).</p>
<p>When combined, the resulting/final dataset must have <strong>at least 4 different variables (at least 3 numeric) in addition to the common variable</strong> (i.e., five variables total).</p>
<p>You can have as many variables as you would like! If you found two datasets that you like but they don’t have enough variables, find a third dataset with the same common variable and join all three.</p>
</div>
<div id="guidelines" class="section level3">
<h3>Guidelines</h3>
<ol style="list-style-type: decimal">
<li><p>If the datasets are not tidy, you will need to reshape them so that every observation has its own row and every variable its own column. If the datasets are both already tidy, you will make them untidy with <code>pivot_wider()/spread()</code> and then tidy them again with <code>pivot_longer/gather()</code> to demonstrate your use of the functions. It’s fine to wait until you have your descriptives to use these functions (e.g., you might want to pivot_wider() to rearrange the data to make your descriptive statistics easier to look at); it’s fine long as you use them at least once!</p>
<ul>
<li><p>Depending on your datasets, it might be a good idea to do this before joining. For example, if you have a dataset you like with multiple measurements per year, but you want to join by year, you could average over your numeric variables to get means/year, do counts for your categoricals to get a counts/year, etc.</p></li>
<li><p>If your data sets are already tidy, demonstrate the use of <code>pivot_longer()/gather()</code> and <code>pivot_wider()/spread()</code> on all or part of your data at some point in this document (e.g., after you have generated summary statistics in part 3, make a table of them wide instead of long).</p></li>
</ul></li>
</ol>
<pre class="r"><code>library(tidyverse)

obesity_data &lt;- read_csv(&quot;obesity.csv&quot;)
health_data &lt;- read_csv(&quot;health_systems.csv&quot;)
happiness_data &lt;- read_csv(&quot;happiness.csv&quot;)</code></pre>
<p>For this project, there were three datasets used. The first dataset documents the prevalance of obesity (BMI ≥ 30) by each sex in countries across the world and was collected by the World Health Organization on their website. The dataset only contains 2 variables, the prevalance of obesity in males and the prevelance of obesity in females. The most recent update of data collected was from 2016. The second dataset reports the state of health systems in countries obtained from Kaggle. There are a total of 14 variables in this dataset, 3 of which are different methods to categorize the country and state where the information was collected, and the remaining are numeric variables that are measures of the health system of that country. For example, there is a column that reports the current health expenditure as a percent of GDP, another that reports the amount of out of pocket costs of healthcare for a household, and another column reports the number of physicians per 1000 people. The last dataset is data reporting the state of happiness in different countries based on variables like the GDP, the life expectancy, and the healthy life expectancy and the rank of the happiness of all the countries where data was collected obtained from Kaggle. The dataset has a total of 13 variables but only 4 are relevant because they give the country, region, happiness score, and happiness ranking. The remaining variables describe how the happiness score was calculated but doesn’t give data that is relevant for analysis so they will be dropped. The three datasets were selected based on an interest for public health. As a premed student that was studied public health and analyzed factors of healthy in both developed and under developed countries, I wanted to compare the happiness of inidivduals, the prevalance of obesity which is an increasingly important problem, and the state of health systems of each country throughout the world. I believed that all three datasets are an important measure of a country’s state.</p>
<ol start="2" style="list-style-type: decimal">
<li><p>Join your 2+ separate data sources into a single dataset based on a common ID variable! If you can’t find a good pair datasets to join, you may split one main dataset into two different datasets with a common ID variable in each, and then join them back together based on that common ID, but this is obviously less than ideal.</p>
<ul>
<li>You will document the type of join that you do (left/right/inner/full), including a discussion of how many observations were in each dataset, which observations in each dataset were dropped (if any) and why you chose this particular join.</li>
</ul></li>
</ol>
<pre class="r"><code>nrow(obesity_data)</code></pre>
<pre><code>## [1] 193</code></pre>
<pre class="r"><code>nrow(health_data)</code></pre>
<pre><code>## [1] 210</code></pre>
<pre class="r"><code>join_data &lt;- obesity_data %&gt;% na.omit() %&gt;% full_join(health_data, by = c(&quot;Country&quot; = &quot;World_Bank_Name&quot;)) %&gt;% arrange(Country)
nrow(join_data)</code></pre>
<pre><code>## [1] 221</code></pre>
<pre class="r"><code>join_data &lt;- join_data %&gt;% left_join(happiness_data, by = &quot;Country&quot;)
join_data &lt;- join_data %&gt;% select(1:19, -Country_Region, -Province_State) %&gt;% 
  rename(male_obesity = Male) %&gt;% rename(female_obesity = Female)</code></pre>
<p>The obesity dataset has 193 observations and the health_systems dataset has 210 observations. After running an full_join, the dataset has 223 observations. First, all observations in obesity that had NAs were dropped because there were only two variables so any missing data would not provide enough information. The join kept all observations in both datasets because both datasets had similar data and any observations that weren’t shared still provided a lot of information. The joined dataset was then joined with a happiness dataset while only keeping all the rows in the original joined dataset with obesity and health_systems observations because the happiness dataset is only used to include supplemental information but isn’t necessary. Only 3 variables, not including the joined variable, was kept from the happiness dataset because the other variables have no impact on the total score that was reported for each country.</p>
<ol start="3" style="list-style-type: decimal">
<li><p>Create summary statistics</p>
<ul>
<li><p>Use <em>all six</em> core <code>dplyr</code> functions (<code>filter, select, arrange, group_by, mutate, summarize</code>) to manipulate and explore your dataset. For mutate, create a new variable that is a function of at least one other variable, preferably using a dplyr vector function (see dplyr cheatsheet). It’s totally fine to use the <code>_if</code>, <code>_at</code>, <code>_all</code> versions of mutate/summarize instead (indeed, it is encouraged if you have lots of variables)</p></li>
<li><p>Create summary statistics (<code>mean, sd, var, n, quantile, min, max, n_distinct, cor</code>, etc) for each of your numeric variables both overall and after grouping by one of your categorical variables (either together or one-at-a-time; if you have two categorical variables, try to include at least one statistic based on a grouping of two categorical variables simultaneously). If you do not have any categorical variables, create one using mutate (e.g., with <code>case_when</code> or <code>ifelse</code>) to satisfy the <code>group_by</code> requirements above. Ideally, you will find a way to show these summary statistics in an easy-to-read table (e.g., by reshaping). (You might explore the kable package for making pretty tables!) If you have lots of numeric variables (e.g., 10+), or your categorical variables have too many categories, just pick a few (either numeric variables or categories of a categorical variable) and summarize based on those. It would be a good idea to show a correlation matrix for your numeric variables (you will need it to make one of your plots).</p></li>
</ul></li>
</ol>
<pre class="r"><code>join_data &lt;- join_data %&gt;% mutate(avg_obesity = (male_obesity + female_obesity)/2) 
join_data &lt;- join_data %&gt;% select(1, Region, avg_obesity, male_obesity, female_obesity, everything())
join_data &lt;- join_data %&gt;% rename(exp_pct_GDP = Health_exp_pct_GDP_2016,
                                  exp_domestic_fund = Health_exp_public_pct_2016,
                                  out_pocket = Health_exp_out_of_pocket_pct_2016,
                                  exp_percapita_USD = Health_exp_per_capita_USD_2016,
                                  exp_percapita_PPP = per_capita_exp_PPP_2016,
                                  exp_ext_fund = External_health_exp_pct_2016,
                                  phys_per1000 = &#39;Physicians_per_1000_2009-18&#39;,
                                  nur_per1000 = &#39;Nurse_midwife_per_1000_2009-18&#39;,
                                  spec_per1000 = &#39;Specialist_surgical_per_1000_2008-18&#39;,
                                  birth_reg = &#39;Completeness_of_birth_reg_2009-18&#39;,
                                  death_reg = &#39;Completeness_of_death_reg_2008-16&#39;)
join_data %&gt;% summarise(distinct_country = n_distinct(Country), distinct_regions = n_distinct(Region))</code></pre>
<pre><code>## # A tibble: 1 x 2
##   distinct_country distinct_regions
##              &lt;int&gt;            &lt;int&gt;
## 1              221               11</code></pre>
<pre class="r"><code>join_data %&gt;% filter(Happiness_Rank &gt; median(Happiness_Rank, na.rm = TRUE)) %&gt;% 
  group_by(Region) %&gt;% summarise(counts = n()) %&gt;% arrange(counts)</code></pre>
<pre><code>## # A tibble: 8 x 2
##   Region                          counts
##   &lt;chr&gt;                            &lt;int&gt;
## 1 Eastern Asia                         2
## 2 Western Europe                       2
## 3 Latin America and Caribbean          3
## 4 Southeastern Asia                    6
## 5 Southern Asia                        7
## 6 Middle East and Northern Africa      8
## 7 Central and Eastern Europe          13
## 8 Sub-Saharan Africa                  34</code></pre>
<pre class="r"><code>join_data %&gt;% group_by(Region) %&gt;% summarise(all_region = (n())) %&gt;% arrange(all_region)</code></pre>
<pre><code>## # A tibble: 11 x 2
##    Region                          all_region
##    &lt;chr&gt;                                &lt;int&gt;
##  1 Australia and New Zealand                2
##  2 North America                            2
##  3 Eastern Asia                             5
##  4 Southern Asia                            7
##  5 Southeastern Asia                        9
##  6 Middle East and Northern Africa         17
##  7 Western Europe                          20
##  8 Latin America and Caribbean             24
##  9 Central and Eastern Europe              29
## 10 Sub-Saharan Africa                      36
## 11 &lt;NA&gt;                                    70</code></pre>
<pre class="r"><code>corr_mat &lt;- join_data %&gt;% select_if(is.numeric) %&gt;% cor(use = &quot;pair&quot;)
join_data %&gt;% arrange(-Happiness_Rank) %&gt;% select(1, Happiness_Rank, exp_domestic_fund) </code></pre>
<pre><code>## # A tibble: 221 x 3
##    Country                     Happiness_Rank exp_domestic_fund
##    &lt;chr&gt;                                &lt;dbl&gt;             &lt;dbl&gt;
##  1 Burundi                                157              29.1
##  2 Syrian Arab Republic                   156             NaN  
##  3 Togo                                   155              20  
##  4 Afghanistan                            154               5.1
##  5 Benin                                  153              20.5
##  6 Rwanda                                 152              33.9
##  7 Guinea                                 151              12.3
##  8 Liberia                                150              14.2
##  9 United Republic of Tanzania            149              40.6
## 10 Madagascar                             148              47.7
## # … with 211 more rows</code></pre>
<pre class="r"><code>join_data %&gt;% arrange(-exp_pct_GDP) %&gt;% select(1, exp_pct_GDP, nur_per1000)</code></pre>
<pre><code>## # A tibble: 221 x 3
##    Country                  exp_pct_GDP nur_per1000
##    &lt;chr&gt;                          &lt;dbl&gt;       &lt;dbl&gt;
##  1 Marshall Islands                23.3         3.5
##  2 United States of America        17.1         8.6
##  3 Sierra Leone                    16.5         1  
##  4 Tuvalu                          15.5         3.8
##  5 Fed. Sts. Micronesia            12.6         3.3
##  6 Cuba                            12.2         7.8
##  7 Switzerland                     12.2        17.3
##  8 Kiribati                        11.9         4.8
##  9 Brazil                          11.8         9.7
## 10 Palau                           11.7         5.3
## # … with 211 more rows</code></pre>
<p>The first step was to add a new column using mutate called avg_obesity which is the average prevalance of obesity across both sexes since it would be easier to analyze obesity data with other variables when there is already an average prevalance calculated for a country. For visual purporses, the columns were rearranged using select so that the categorical variables (country and region) came first, because the data will joined based on country and grouped by region, followed by obesity data then health standards data and happiness rank and score last. The variable names were also changed using rename in order to clean up the tables from the long variable names which will help with future plotting. Next, countries were filtered based on ones that had a happiness ranking that is greater than the median happiness rank (ranked as less happy than other countries) then grouped by country to get a count of the number of countries in each region where the happiness rank is greater than the median. It was found that Eastern Asia and Western Europe has the least, only 2 countries, where the happiness rank is greater than the median but it must be noted that there are 10 distinct regions so 2, Australia and New Zealand and North America, don’t have any countries that have a happiness rank that is greater than the median. The higher the happiness rank, the less happy the country is in comparison to other countries, so Sub-Saharan Africa has the greatest number of countries, 34, that rank above the median happiness ranking. A correlation matrix was created to analyze if there was a correlation between any of the numeric variables. Some correlations that are of interest include the reasonably strong negative correlation between the happiness rank and the variable exp_domestic_fund, or the domestic general government health expenditure, and reasonably strong positive correlation between nur_per1000 (number of nurses per 1000 people) and both exp_percapita_USD and exp_percapita_PPP. This can be generalized to the more a country spends on health per capita, the more nurses there are available. The data was arranged to display the columns that were of interest from the correlation matrix.</p>
<pre class="r"><code>join_data %&gt;% group_by(Region) %&gt;% summarise(avg_happiness_rank = mean(Happiness_Rank, na.rm = TRUE)) %&gt;% arrange(avg_happiness_rank)</code></pre>
<pre><code>## # A tibble: 11 x 2
##    Region                          avg_happiness_rank
##    &lt;chr&gt;                                        &lt;dbl&gt;
##  1 Australia and New Zealand                      8.5
##  2 North America                                  9.5
##  3 Western Europe                                27.6
##  4 Latin America and Caribbean                   48.3
##  5 Middle East and Northern Africa               72.3
##  6 Eastern Asia                                  73.8
##  7 Central and Eastern Europe                    78.4
##  8 Southeastern Asia                             80  
##  9 Southern Asia                                112. 
## 10 Sub-Saharan Africa                           130. 
## 11 &lt;NA&gt;                                         NaN</code></pre>
<pre class="r"><code>join_data %&gt;% group_by(Region) %&gt;% summarise(avg_female_obesity = mean(female_obesity, na.rm = TRUE),
                                             avg_male_obesity = mean(male_obesity, na.rm = TRUE))</code></pre>
<pre><code>## # A tibble: 11 x 3
##    Region                          avg_female_obesity avg_male_obesity
##    &lt;chr&gt;                                        &lt;dbl&gt;            &lt;dbl&gt;
##  1 Australia and New Zealand                    31.5             30.8 
##  2 Central and Eastern Europe                   24.6             21.2 
##  3 Eastern Asia                                  9.72             8.02
##  4 Latin America and Caribbean                  27.9             18.1 
##  5 Middle East and Northern Africa              36.6             24.4 
##  6 North America                                34.8             33.8 
##  7 Southeastern Asia                             8.28             5.31
##  8 Southern Asia                                 6.53             3.3 
##  9 Sub-Saharan Africa                           12.3              4.01
## 10 Western Europe                               24.0             25.1 
## 11 &lt;NA&gt;                                         28.9             19.0</code></pre>
<pre class="r"><code>join_data %&gt;% group_by(Region) %&gt;% summarise(avg_region_obesity = mean(avg_obesity, na.rm = TRUE),
                                             sd_avg_obesity = sd(avg_obesity, na.rm = TRUE),
                                             avg_happy_score = mean(Happiness_Score, na.rm = TRUE),
                                             avg_per_precent_GDP = mean(exp_pct_GDP, na.rm = TRUE),
                                             sd_per_percent_GDP = sd(exp_pct_GDP, na.rm = TRUE),
                                             avg_out_pocket = mean(out_pocket, na.rm = TRUE),
                                             avg_per_capita = mean(exp_percapita_PPP, na.rm = TRUE),
                                             sd_per_capita = sd(exp_percapita_PPP, na.rm = TRUE))</code></pre>
<pre><code>## # A tibble: 11 x 9
##    Region avg_region_obes… sd_avg_obesity avg_happy_score avg_per_precent…
##    &lt;chr&gt;             &lt;dbl&gt;          &lt;dbl&gt;           &lt;dbl&gt;            &lt;dbl&gt;
##  1 Austr…            31.2            1.10            7.32             9.25
##  2 Centr…            22.9            4.17            5.37             7.04
##  3 Easte…             8.88           7.18            5.47             6.75
##  4 Latin…            23.0            3.60            6.10             7.18
##  5 Middl…            30.5            4.16            5.52             5.44
##  6 North…            34.4            4.24            7.25            13.8 
##  7 South…             6.79           3.98            5.34             4.31
##  8 South…             4.91           1.58            4.56             4.69
##  9 Sub-S…             8.16           4.42            4.12             5.99
## 10 Weste…            24.6            2.69            6.73             9.52
## 11 &lt;NA&gt;              24.0           16.3           NaN                6.43
## # … with 4 more variables: sd_per_percent_GDP &lt;dbl&gt;, avg_out_pocket &lt;dbl&gt;,
## #   avg_per_capita &lt;dbl&gt;, sd_per_capita &lt;dbl&gt;</code></pre>
<pre class="r"><code>join_data %&gt;% summarise(quan_obesity = quantile(avg_obesity, na.rm = TRUE),
                        quan_percent_GDP = quantile(exp_pct_GDP, na.rm = TRUE),
                        quan_out_pocket = quantile(out_pocket, na.rm = TRUE),
                        quan_per_capita = quantile(exp_percapita_PPP, na.rm = TRUE))</code></pre>
<pre><code>## # A tibble: 5 x 4
##   quan_obesity quan_percent_GDP quan_out_pocket quan_per_capita
##          &lt;dbl&gt;            &lt;dbl&gt;           &lt;dbl&gt;           &lt;dbl&gt;
## 1         2.1              1.7              0.1            29.9
## 2         8.18             4.5             16.2           232. 
## 3        21.2              6.2             30.1           782. 
## 4        26.6              8.38            44.8          1886. 
## 5        60.8             23.3             81            9870.</code></pre>
<p>A series of means and other statistics were calculated using summarize in order to study each of the variables in the joined dataset. An average happiness rank was calculated for each region using group_by then arrange in ascending order and based on the calculation, countries in Australia and New Zealand and North America are ranked higher on average in terms of happiness in comparison to countries in Southern and Asia and Sub-Saharan Africa which rank second to last and last respectively. The average obesity for each sex was calculated based on group_by region which shows that there is a difference in prevalance of obsesity by sex but using an average obesity with both sexes makes analyzing the data more efficient. A summary of means and standard deviations for various variables was performed on groups of countries by region to find an average of statistics like obesity prevalance, health expenditure per GDP, average out of pocket health care costs for a household by country, and some others to just get an understanding of each variable. The quantile of several variables were calculated in order to compare with the previous mean calculations by region to identify where each region falls on the quantile summaries for different variables. The summary statistics gave information about the data that was helpful in determining which variables should be plotted to study relationships.</p>
<pre class="r"><code>joined_professionals &lt;- join_data %&gt;% pivot_longer(c(&quot;phys_per1000&quot;, &quot;nur_per1000&quot;, &quot;spec_per1000&quot;), 
                           names_to = &quot;med_professional&quot;, values_to = &quot;num_professionals&quot;)
joined_obesity &lt;- join_data %&gt;% pivot_longer(c(male_obesity, female_obesity), 
                                             names_to = &quot;sex&quot;, values_to = &quot;obesity_prevalance&quot;) 
joined_professionals %&gt;% pivot_wider(names_from = &quot;med_professional&quot;, values_from = &quot;num_professionals&quot;) </code></pre>
<pre><code>## # A tibble: 221 x 18
##    Country Region avg_obesity male_obesity female_obesity exp_pct_GDP
##    &lt;chr&gt;   &lt;chr&gt;        &lt;dbl&gt;        &lt;dbl&gt;          &lt;dbl&gt;       &lt;dbl&gt;
##  1 Afghan… South…        4.45          2.7            6.2        10.2
##  2 Albania Centr…       22.4          21.9           22.8         6.7
##  3 Algeria Middl…       26.7          19.4           34           6.6
##  4 Andorra &lt;NA&gt;         28            27.9           28.1        10.4
##  5 Angola  Sub-S…        6.75          3.5           10           2.9
##  6 Antigu… &lt;NA&gt;         19            11.7           26.3         4.3
##  7 Argent… Latin…       28.5          27.4           29.6         7.5
##  8 Armenia Centr…       20.8          17.2           24.5         9.9
##  9 Austra… Austr…       30.4          30.7           30.1         9.3
## 10 Austria Weste…       22            23.4           20.6        10.4
## # … with 211 more rows, and 12 more variables: exp_domestic_fund &lt;dbl&gt;,
## #   out_pocket &lt;dbl&gt;, exp_percapita_USD &lt;dbl&gt;, exp_percapita_PPP &lt;dbl&gt;,
## #   exp_ext_fund &lt;dbl&gt;, birth_reg &lt;dbl&gt;, death_reg &lt;dbl&gt;, Happiness_Rank &lt;dbl&gt;,
## #   Happiness_Score &lt;dbl&gt;, phys_per1000 &lt;dbl&gt;, nur_per1000 &lt;dbl&gt;,
## #   spec_per1000 &lt;dbl&gt;</code></pre>
<p>Since the dataset that was joined from the three individual datasets was already tidy, some examples of tidying was shown here as examples. A pivot longer was first done on the joined dataset that rearranged three variables with the counts of various medical professionals per 1000 people like nurses, physicians, and specialists into one variable that had all of the medical professionals together. This was saved as joined_professionals to demonstrate a pivot_wider to undo the combination of the three variables. The second pivot_longer was saved as joined_obesity as joins the data of two variables, the prevalance of obesity in males and the prevalance of obesity in females into a single column with both variables. This rearranged tidy dataset is needed later to plot the difference in obesity prevalance between sexes for each region.</p>
<ol start="4" style="list-style-type: decimal">
<li><p>Make visualizations (three plots)</p>
<ul>
<li>Make a correlation heatmap of your numeric variables</li>
<li>Create at least two additional plots of your choice with ggplot that highlight some of the more interesting features of your data.</li>
<li>Each plot (besides the heatmap) should have at least three variables mapped to separate aesthetics</li>
<li>Each should use different geoms (don’t do two geom_bars)</li>
<li>At least one plot should include <code>stat="summary"</code></li>
<li>Each plot should include a supporting paragraph describing the relationships that are being visualized and any trends that are apparent
<ul>
<li>It is fine to include more, but limit yourself to 4. Plots should avoid being redundant! Four bad plots will get a lower grade than two good plots, all else being equal.</li>
</ul></li>
<li>Make them pretty! Use correct labels, etc.</li>
</ul></li>
</ol>
<pre class="r"><code>tidy_corr &lt;- corr_mat %&gt;% as.data.frame() %&gt;% rownames_to_column(&quot;var1&quot;) %&gt;% 
  pivot_longer(-1, names_to = &quot;var2&quot;, values_to = &quot;correlation&quot;)
tidy_corr %&gt;% ggplot(aes(var1, var2, fill = correlation)) + geom_tile() + 
  scale_fill_gradient2(low=&quot;red&quot;,mid=&quot;white&quot;,high=&quot;blue&quot;) + 
  geom_text(aes(label=round(correlation,2)),color = &quot;black&quot;, size = 2) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + coord_fixed() </code></pre>
<p><img src="/project/project1_files/figure-html/unnamed-chunk-6-1.png" width="960" style="display: block; margin: auto;" /></p>
<pre class="r"><code>joined_obesity %&gt;% drop_na(Region) %&gt;% ggplot(aes(x = Region, y = obesity_prevalance, fill = sex)) + 
  geom_bar(stat = &quot;summary&quot;, position = &quot;dodge&quot;) + geom_errorbar(stat = &quot;summary&quot;, position = &quot;dodge&quot;) +
  theme(axis.text.x = element_text(angle = 60, hjust = 1)) + scale_fill_discrete(labels = c(&quot;female&quot;, &quot;male&quot;)) + 
  ggtitle(&quot;Obesity Prevalance for Each Sex by Region&quot;) + ylab(&quot;Obesity Prevalance&quot;)</code></pre>
<p><img src="/project/project1_files/figure-html/unnamed-chunk-7-1.png" width="672" style="display: block; margin: auto;" />
A pivot longer performed previously and saved as joined_obesity was used in order to map the prevalance of obesity of each sex to an aesthetic. The obesity prevalance for each region was plotted based on sex and most of the countries appear to have relatively the same obesity prevalance for both sexes excpet for a few. Most notably, in Latin America and the Caribbean, Middle East and Northern Africa, and Sub-Saharan Africa there is a significantly higher obesity prevalance in females in comparison to males. In addition, when comparing obesity prevalance between regions, more developed areas of the world like North America, Australia and New Zealand, and Europe have a much higher obesity prevalance in comparison to developing regions like Eastern Asia, Southeastern Asian, Southern Asian and Sub-Saharan Africa.</p>
<pre class="r"><code>join_data %&gt;% ggplot(aes(exp_percapita_PPP, nur_per1000)) + 
  geom_point(aes(color = Region)) + geom_smooth(method = &quot;lm&quot;) +
  ggtitle(&quot;Number of Nurses vs. Health Expenditures per Capita&quot;) +
  scale_x_continuous(breaks = seq(0, 10000, 1000)) + scale_y_continuous(breaks = seq(0, 22, 2)) +
  xlab(&quot;Health Expenditures per Capita in International Dollars at PPP&quot;) + ylab(&quot;Number of Nurses per 1000&quot;)</code></pre>
<p><img src="/project/project1_files/figure-html/unnamed-chunk-8-1.png" width="672" style="display: block; margin: auto;" />
The plot above plots points of all countries by the number of nurses (per 1000) and the current expenditures on health per capita expressed in international dollars at purchasing power parity (PPP). The points are also colored by region to observe groupings of countries in a region on different areas of the plot. The plot was selected based on a reasonably strong positive correlation between the two variables from the correlation matrix and heat map. As the health expenditures per capita at PPP increases, there is an increase in the number of nurses per 1000 people so the more a country spends on their health care, the more number of nurses can be found per 1000 people. In addition, the color grouping of pink points reveals that many Western European countries spend more on health expenditures per capita in international dollars at PPP so they also have more nurses per 1000 people. In comparison, countries in Sub-Saharan Africa have a lower health expenditures per capita in international dollars at PPP so they have less nurses per 1000 people. Lastly, most of the countries in Central and Eastern Europe are plotted near each other as well as countries in Latin America and the Carribean but countries in Central and Eastern Europe have more nurses per health expenditure per capita in comparison to the average (above the linear regression line) while countries in Latin America and the Carribean have less nurses per health expenditure per capita in comparison to the average.</p>
<pre class="r"><code>join_data %&gt;% mutate(happy = ifelse(Happiness_Score &gt; median(Happiness_Score, na.rm = TRUE), 
                                    &quot;greater than median&quot;, &quot;less than median&quot;)) %&gt;%
  drop_na(Region) %&gt;% ggplot(aes(x = happy, y = exp_domestic_fund)) + 
  geom_bar(aes(fill = Region), stat = &quot;summary&quot;, position = &quot;dodge&quot;) + scale_y_continuous(breaks = seq(0, 80, 10)) +
  ggtitle(&quot;Percent of Health Funded Domestically vs. Happiness Score Comparison by Region&quot;) + 
  xlab(&quot;Happiness Score Comparison&quot;) + ylab(&quot;Percent Health Expenditures Funded from Domestic Sources&quot;) + 
  theme(title = element_text(size = 10))</code></pre>
<p><img src="/project/project1_files/figure-html/unnamed-chunk-9-1.png" width="672" style="display: block; margin: auto;" />
The mutate function was used to distinguish if a country has a happiness score that falls above or below the median happiness score. A lower happiness score indicates a lower happiness on average for the country. This was then used to graph bars that show the percentage current health expenditures funded from domestic public sources like internal transfers and grants, transfers, subsidies to voluntary health insurance beneficiaries, etc. Based on the bar plot, all regions with countries that have a happiness score less than the median have their less of their health expenditures funded domestically in comparison to countries that have happiness scores that are greater than the median (more happy). An important example is North America, where both countries in the region have a happiness score that is greater than the median, an extremely large portion of health expenditures is funded domestically.</p>
<ol start="5" style="list-style-type: decimal">
<li><p>Perform k-means/PAM clustering or PCA on (at least) your numeric variables.</p>
<ul>
<li><p>Include all steps as we discuss in class, including a visualization.</p></li>
<li><p>If you don’t have at least 3 numeric variables, or you want to cluster based on categorical variables too, convert them to factors in R, generate Gower’s dissimilarity matrix on the data, and do PAM clustering on the dissimilarities.</p></li>
<li><p>Show how you chose the final number of clusters/principal components</p></li>
<li><p>Interpret the final clusters/principal components</p></li>
<li><p>For every step, document what your code does (in words) and what you see in the data!</p></li>
</ul></li>
</ol>
<pre class="r"><code>library(cluster)
library(GGally)

join_data_na &lt;- join_data %&gt;% na.omit()
clust_data &lt;- join_data_na %&gt;% select(exp_percapita_PPP, nur_per1000, exp_domestic_fund) %&gt;% scale %&gt;% as.data.frame
sil_width &lt;- vector()
for(i in 2:10){  
  pam_fit &lt;- pam(clust_data, k = i)  
  sil_width[i] &lt;- pam_fit$silinfo$avg.width  
}
ggplot() + geom_line(aes(x = 1:10, y = sil_width)) + scale_x_continuous(name = &quot;k&quot;, breaks = 1:10)</code></pre>
<p><img src="/project/project1_files/figure-html/unnamed-chunk-10-1.png" width="672" style="display: block; margin: auto;" />
The first step was to remove all the rows that have an na then process the joined dataset by selecting three numeric variables- exp_percapita_PPP, nur_per1000, exp_domestic_fund- then scaling the variables. A for loop was used to calculated the silhoette widths of different values of k using PAM. Only numeric variables were used so gower was not necessary. After plotting the silhouette widths calculated, the best value for k was determined to 2 as it has the highest silhouette width making the clusters more cohesive and separated.</p>
<pre class="r"><code>pam1 &lt;- clust_data %&gt;% pam(k = 2)
plot(pam1, which = 2)</code></pre>
<p><img src="/project/project1_files/figure-html/unnamed-chunk-11-1.png" width="672" style="display: block; margin: auto;" /></p>
<pre class="r"><code>clust_data &lt;- clust_data %&gt;% mutate(cluster = as.factor(pam1$clustering))

ggpairs(clust_data, columns = 1:3, aes(color = cluster))</code></pre>
<p><img src="/project/project1_files/figure-html/unnamed-chunk-11-2.png" width="672" style="display: block; margin: auto;" /></p>
<pre class="r"><code>clust_data %&gt;% mutate(region = join_data_na$Region) %&gt;% 
  ggplot(aes(x = exp_percapita_PPP, y = nur_per1000, color = region, shape = cluster)) +
  geom_point(size=4) + ggtitle(&quot;Pam Cluster Analysis between Expenditure Per Capita by PPP and Nurses per 1000&quot;) +
  xlab(&quot;Health Expenditures per Capita in International Dollars at PPP&quot;) + ylab(&quot;Number of Nurses per 1000&quot;)</code></pre>
<p><img src="/project/project1_files/figure-html/unnamed-chunk-11-3.png" width="672" style="display: block; margin: auto;" /></p>
<pre class="r"><code>clust_data %&gt;% mutate(region = join_data_na$Region) %&gt;% 
  ggplot(aes(x = exp_domestic_fund, y = nur_per1000, color = region, shape = cluster)) +
  geom_point(size=4) + ggtitle(&quot;Pam Cluster Analysis between Domestically Funded Health and Nurses per 1000&quot;) +
  xlab(&quot;Percent of Health Funded Domestically&quot;) + ylab(&quot;Number of Nurses per 1000&quot;)</code></pre>
<p><img src="/project/project1_files/figure-html/unnamed-chunk-11-4.png" width="672" style="display: block; margin: auto;" />
After finding the optimal value for k, a cluster analysis was run using PAM. When plotted, the average silhouette width was 0.54 which is a reasonable sructure. According to the analysis and the silhouette widths measured, clustering by k = 2 has a reasonably good fit but not strong. By looking at the silhouette widths plotted, each of the points correctly fit in one of the two clusters. Ideally, there should be 10 clusters or one for each of the Regions but based on the cluster analysis run, only 2 were found because of the separation of the data from the variables. The clustering was then added as a variable to clust_data in order to plot each of the countries based on their cluster. The series of plots shows a pairwise combination of the three variables used as the clusters were distinguished by colors in each of the two variables plotted. The clusters were most likely divided on more developed countries that spend more on their health systems and less developed countries that have low health expenditures or a low number of nurses. It was most likely difficult for the cluster analysis to distinguish between regions becuase the main difference between the two clusters found is amount of money dedicated to health expenditures. To confirm this, two different plots were created that plots the shape of the points to one of the two clusters found and color to the original 10 regions. Points in the first cluster were generally regions like Latin America and the Caribbean, Sub-Saharan Africa, or the Middle East and Northern Africa which have countries that are behind in a development standpoint in comparison to countries in the regions more found in the second cluster like Western Europe, Australia and New Zealand, and North America which are generally more developed.</p>
<P style="page-break-before: always">
<div style="page-break-after: always;"></div>
</div>
<div id="rubric" class="section level3">
<h3>Rubric</h3>
<p>Prerequisite: Finding appropriate data from at least two sources per the instructions above: Failure to do this will result in a 0! You will submit a .Rmd file and a knitted document (pdf).</p>
<div id="introduction-4-pts" class="section level4">
<h4>0. Introduction (4 pts)</h4>
<ul>
<li>Write a narrative introductory paragraph or two describing the datasets you have chosen, the variables they contain, how they were acquired, and why they are interesting to you. Expand on potential associations you may expect, if any.</li>
</ul>
</div>
<div id="tidying-rearranging-widelong-8-pts" class="section level4">
<h4>1. Tidying: Rearranging Wide/Long (8 pts)</h4>
<ul>
<li>Tidy the datasets (using the <code>tidyr</code> functions <code>pivot_longer</code>/<code>gather</code> and/or <code>pivot_wider</code>/<code>spread</code>)</li>
<li>If you data sets are already tidy, be sure to use those functions somewhere else in your project</li>
<li>Document the process (describe in words what was done per the instructions)</li>
</ul>
</div>
<div id="joiningmerging-8-pts" class="section level4">
<h4>2. Joining/Merging (8 pts)</h4>
<ul>
<li>Join your datasets into one using a <code>dplyr</code> join function</li>
<li>If you have multiple observations on the joining variable in either dataset, fix this by collapsing via summarize</li>
<li>Discuss the process in words, including why you chose the join you did</li>
<li>Discuss which cases were dropped, if any, and potential problems with this</li>
</ul>
</div>
<div id="wrangling-40-pts" class="section level4">
<h4>3. Wrangling (40 pts)</h4>
<ul>
<li>Use all six core <code>dplyr</code> functions in the service of generating summary statistics (18 pts)
<ul>
<li>Use mutate at least once to generate a variable that is a function of at least one other variable</li>
</ul></li>
<li>Compute at least 10 summary statistics for using summarize and summarize with group_by (18 pts)
<ul>
<li>Use at least 5 unique functions inside of summarize (e.g., mean, sd)</li>
<li>At least 2 of these should group by a categorical variable. Create one by dichotomizing a numeric if necessary</li>
<li>If applicable, at least 1 of these should group by two categorical variables</li>
<li>Strongly encouraged to create a correlation matrix with <code>cor()</code> on your numeric variables</li>
</ul></li>
<li>Summarize/discuss all results in no more than two paragraphs (4 pts)</li>
</ul>
</div>
<div id="visualizing-30-pts" class="section level4">
<h4>4. Visualizing (30 pts)</h4>
<ul>
<li><p>Create a correlation heatmap of your numeric variables</p></li>
<li><p>Create two effective, polished plots with ggplot</p>
<ul>
<li>Each plot should map 3+ variables to aesthetics</li>
<li>Each plot should have a title and clean labeling for all mappings</li>
<li>Change at least one default theme element and color for at least one mapping per plot</li>
<li>For at least one plot, add more tick marks (x, y, or both) than are given by default</li>
<li>For at least one plot, use the stat=“summary” function</li>
<li>Supporting paragraph or two (for each plot) describing the relationships/trends that are apparent</li>
</ul></li>
</ul>
</div>
<div id="dimensionality-reduction-20-pts" class="section level4">
<h4>5. Dimensionality Reduction (20 pts)</h4>
<ul>
<li><p>Either k-means/PAM clustering or PCA (inclusive “or”) should be performed on at least three numeric variables in your dataset</p>
<ul>
<li>All relevant steps discussed in class</li>
<li>A visualization of the clusters or the first few principal components (using ggplot2)</li>
<li>Supporting paragraph or two describing results found</li>
</ul></li>
</ul>
</div>
<div id="neatness" class="section level4">
<h4>6. Neatness!</h4>
<ul>
<li>Your project should not knit to more than 30 or so pages (probably closer to 10)! You will lose points if you print out your entire dataset(s), have terrible formatting, etc. If you start your project in a fresh .Rmd file, you are advised to paste the set-up code from this document (lines 14-17) at the top of it: this will automatically truncate if you accidentally print out a huge dataset, etc. Imagine this is a polished report you are giving to your PI or boss to summarize your work researching a topic.</li>
</ul>
</div>
</div>
<div id="where-do-i-find-data" class="section level3">
<h3>Where do I find data?</h3>
<p>OK, brace yourself!</p>
<p>You can choose ANY datasets you want that meet the above criteria for variables and observations. I’m just sitting here but off the top of my head, if you are into amusement parks, you could look at amusement-park variables, including ticket sales per day etc.; then you could join this by date in weather data. If you are interested in Game of Thrones, you could look at how the frequency of mentions of character names (plus other character variables) and the frequency of baby names in the USA…You could even take your old Biostats data and merge in new data (e.g., based on a Google forms timestamp).</p>
<p>You could engage in some “me-search”: You can <a href="https://support.spotify.com/ca-en/article/data-rights-and-privacy-settings/">request your Spotify data</a> or <a href="https://help.netflix.com/en/node/101917">download Netflix viewing activity</a>, Amazon purchase history, etc. You can use your Google Fit/Fitbit/Apple watch data, etc. These can be combined (e.g., with each other, with other data sources).</p>
<p>You can make it as serious as you want, or not, but keep in mind that you will be incorporating this project into a portfolio webpage for your final in this course, so choose something that really reflects who you are, or something that you feel will advance you in the direction you hope to move career-wise, or something that you think is really neat. On the flip side, regardless of what you pick, you will be performing all the same tasks, so it doesn’t end up being that big of a deal.</p>
<p>If you are totally clueless and have no direction at all, log into the server and type</p>
<pre class="r"><code>data(package = .packages(all.available = TRUE))</code></pre>
<p>This will print out a list of <strong>ALL datasets in ALL packages</strong> installed on the server (a ton)! Scroll until your eyes bleed! Actually, do not scroll that much… To start with something more manageable, just run the command on your own computer, or just run <code>data()</code> to bring up the datasets in your current environment. To read more about a dataset, do <code>?packagename::datasetname</code>.</p>
<p>If it is easier for you, and in case you don’t have many packages installed, a list of R datasets from a few common packages (also downloadable in CSV format) is given at the following website: <a href="https://vincentarelbundock.github.io/Rdatasets/datasets.html" class="uri">https://vincentarelbundock.github.io/Rdatasets/datasets.html</a> (including types/numbers of variables in each)</p>
<ul>
<li><p>A good package to download for fun/relevant data is <code>fivethiryeight</code>. Just run <code>install.packages("fivethirtyeight"), load the packages with</code>library(fivethirtyeight)<code>, run</code>data()`, and then scroll down to view the datasets. Here is an online list of all 127 datasets (with links to the 538 articles). Lots of sports, politics, current events, etc: <a href="https://cran.r-project.org/web/packages/fivethirtyeight/vignettes/fivethirtyeight.html" class="uri">https://cran.r-project.org/web/packages/fivethirtyeight/vignettes/fivethirtyeight.html</a></p></li>
<li><p>If you have already started to specialize (e.g., ecology, epidemiology) you might look at discipline-specific R packages (vegan, epi, respectively). We will be using some tools from these packages later in the course, but they come with lots of data too, which you can explore according to the directions above</p></li>
<li><p>However, you <em>emphatically DO NOT</em> have to use datasets available via R packages! In fact, I would much prefer it if you found the data from completely separate sources and brought them together (a much more realistic experience in the real world)! You can even reuse data from your SDS328M project, provided it shares a variable in common with other data which allows you to merge the two together (e.g., if you still had the timestamp, you could look up the weather that day: <a href="https://www.wunderground.com/history/" class="uri">https://www.wunderground.com/history/</a>). If you work in a research lab or have access to old data, you could potentially merge it with new data from your lab!</p></li>
<li><p>Here is a curated list of interesting datasets (read-only spreadsheet format): <a href="https://docs.google.com/spreadsheets/d/1wZhPLMCHKJvwOkP4juclhjFgqIY8fQFMemwKL2c64vk/edit" class="uri">https://docs.google.com/spreadsheets/d/1wZhPLMCHKJvwOkP4juclhjFgqIY8fQFMemwKL2c64vk/edit</a></p></li>
<li><p>Here is another great compilation of datasets: <a href="https://github.com/rfordatascience/tidytuesday" class="uri">https://github.com/rfordatascience/tidytuesday</a></p></li>
<li><p>Here is the UCI Machine Learning Repository: <a href="https://archive.ics.uci.edu/ml/index.php" class="uri">https://archive.ics.uci.edu/ml/index.php</a></p>
<ul>
<li>See also <a href="https://en.wikipedia.org/wiki/List_of_datasets_for_machine-learning_research#Biological_data" class="uri">https://en.wikipedia.org/wiki/List_of_datasets_for_machine-learning_research#Biological_data</a></li>
</ul></li>
<li><p>Here is another good general place to look: <a href="https://www.kaggle.com/datasets" class="uri">https://www.kaggle.com/datasets</a></p></li>
<li><p>To help narrow your search down or to see interesting variable ideas, check out <a href="https://www.tylervigen.com/spurious-correlations" class="uri">https://www.tylervigen.com/spurious-correlations</a>. This is the spurious correlations website, and it is fun, but if you look at the bottom of each plot you will see sources for the data. This is a good place to find very general data (or at least get a sense of where you can scrape data together from)!</p></li>
<li><p>If you are interested in medical data, check out www.countyhealthrankings.org</p></li>
<li><p>If you are interested in scraping UT data, the university makes <em>loads</em> of data public (e.g., beyond just professor CVs and syllabi). Check out all the data that is available in the statistical handbooks: <a href="https://reports.utexas.edu/statistical-handbook" class="uri">https://reports.utexas.edu/statistical-handbook</a></p></li>
</ul>
<div id="broader-data-sources" class="section level5">
<h5>Broader data sources:</h5>
<p><a href="www.data.gov">Data.gov</a> 186,000+ datasets!</p>
<p><a href="Social%20Explorer">Social Explorer</a> is a nice interface to Census and American Community Survey data (more user-friendly than the government sites). May need to sign up for a free trial.</p>
<p><a href="www.bls.gov">U.S. Bureau of Labor Statistics</a></p>
<p><a href="www.census.gov">U.S. Census Bureau</a></p>
<p><a href="www.gapminder.org/data">Gapminder</a>, data about the world.</p>
<p>…</p>
</div>
</div>
</div>

            
        <hr>         <div class="related-posts">
                <h5>Related Posts</h5>
                
              </div> 
            </div>
          </div>

   <hr>  <div class="disqus">
  <div id="disqus_thread"></div>
  <script type="text/javascript">

    (function() {
      
      
      if (window.location.hostname == "localhost")
        return;

      var disqus_shortname = '';
      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
  </script>
  <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
  <a href="http://disqus.com/" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
</div> 
        </div>
      </div>
    </div>

    
    <footer>
  <div id="footer">
    <div class="container">
      <p class="text-muted">&copy; All rights reserved. Powered by <a href="https://gohugo.io/">Hugo</a> and
      <a href="http://www.github.com/nurlansu/hugo-sustain/">sustain</a> with ♥</p>
    </div>
  </div>
</footer>
<div class="footer"></div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="/js/docs.min.js"></script>
<script src="/js/main.js"></script>

<script src="/js/ie10-viewport-bug-workaround.js"></script>


    
  </body>
</html>
