<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Charleen Ta" />
    
    <link rel="shortcut icon" type="image/x-icon" href="/img/favicon.ico">
    <title>Project 2: Modeling, Testing, and Predicting</title>
    <meta name="generator" content="Hugo 0.79.0" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="/css/main.css" />
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,400,200bold,400old" />
    
    <!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->

    
  </head>

  <body>
    <div id="wrap">
      
      <nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/"><i class="fa fa-home"></i></a>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse" id="navbar">
      <ul class="nav navbar-nav navbar-right">
      
        
        <li><a href="/post/">BLOG</a></li>
        
        <li><a href="/projects/">PROJECTS</a></li>
        
        <li><a href="/resume/">RESUME</a></li>
        
      
      </ul>
    </div>
  </div>
</nav>

      <div class="container">
        <div class="blog-post">
          <h3>
            <strong><a href="/project/project2/">Project 2: Modeling, Testing, and Predicting</a></strong>
          </h3>
        </div>
 
<div class="blog-title">
          <h4>
         January 1, 0001 
            &nbsp;&nbsp;
            
          </h4>
        </div>

        <div class="panel panel-default">
          <div class="panel-body">
            <div class="blogpost">
              


<div id="modeling" class="section level1">
<h1>Modeling</h1>
<div id="instructions" class="section level2">
<h2>Instructions</h2>
<p>A knitted R Markdown document (preferably HTML) and the raw R Markdown file (as .Rmd) should both be submitted to Canvas by 11:59pm on the due date. These two documents will be graded jointly, so they must be consistent (i.e., don’t change the R Markdown file without also updating the knitted document). Knit an html copy too, for later! In the .Rmd file for Project 2, you can copy the first code-chunk into your project .Rmd file to get better formatting. Notice that you can adjust the opts_chunk$set(…) above to set certain parameters if necessary to make the knitting cleaner (you can globally set the size of all plots, etc). You can copy the set-up chunk in Project2.Rmd: I have gone ahead and set a few for you (such as disabling warnings and package-loading messges when knitting)!</p>
<p>Like before, I envision your written text forming something of a narrative structure around your code/output. All results presented must have corresponding code. Any answers/results/plots etc. given without the corresponding R code that generated the result will not be graded. Furthermore, all code contained in our project document should work properly. Please do not include any extraneous code or code which produces error messages. (Code which produces warnings is fine as long as you understand what the warnings mean.)</p>
</div>
<div id="find-data" class="section level2">
<h2>Find data:</h2>
<p>Find one dataset with at least 5 variables (ideally more!) that you want to use to build models/test hypotheses. At least one should be categorical (with 2-5 groups, ideally; definitely fewer than 10) and at least two should be numeric (taking on more than 10 distinct values). Ideally, at least of your variables will be binary (if not, you will have to create one by discretizing a numeric or collapsing levels of a categorical). You will need a minimum of 40 observations (<em>at least</em> 10 observations for every explanatory variable you have, ideally 20+ observations/variable).</p>
<p>It is perfectly fine to use either dataset (or the merged dataset, or a subset of your variables) from Project 1. However, I might encourage you to diversify things a bit and choose a different dataset to work with (particularly if the variables did not reveal interesting associations in Project 1 that you want to follow up with). The only requirement/restriction is that you may not use data from any examples we have done in class or lab. It would be a good idea to pick more cohesive data this time around (i.e., variables that you actually thing might have a relationship you would want to test). Think more along the lines of your Biostats project.</p>
<p>Again, you can use data from anywhere you want (see bottom for resources)! If you want a quick way to see whether a built-in (R) dataset has binary and/or character (i.e., categorical) variables, check out this list: <a href="https://vincentarelbundock.github.io/Rdatasets/datasets.html" class="uri">https://vincentarelbundock.github.io/Rdatasets/datasets.html</a>.</p>
</div>
<div id="guidelines-and-rubric" class="section level2">
<h2>Guidelines and Rubric</h2>
<ul>
<li><strong>0. (5 pts)</strong> Introduce your dataset and each of your variables (or just your main variables if you have lots) in a paragraph. What are they measuring? How many observations?</li>
</ul>
<pre class="r"><code>cardio_data &lt;- read_csv(&quot;cardio_health.csv&quot;)

nrow(cardio_data)</code></pre>
<pre><code>## [1] 4238</code></pre>
<pre class="r"><code>ncol(cardio_data)</code></pre>
<pre><code>## [1] 16</code></pre>
<pre class="r"><code>head(cardio_data)</code></pre>
<pre><code>## # A tibble: 6 x 16
## id age education sex is_smoking cigsPerDay BPMeds
prevalentStroke prevalentHyp diabetes
## &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
&lt;dbl&gt;
## 1 0 64 2 F YES 3 0 0 0 0
## 2 1 36 4 M NO 0 0 0 1 0
## 3 2 46 1 F YES 10 0 0 0 0
## 4 3 50 1 M YES 20 0 0 1 0
## 5 4 64 1 F YES 30 0 0 0 0
## 6 5 61 3 F NO 0 0 0 1 0
## # … with 6 more variables: chol &lt;chr&gt;, sysBP &lt;dbl&gt;,
diaBP &lt;dbl&gt;, BMI &lt;dbl&gt;, heartRate &lt;dbl&gt;,
## # glucose &lt;dbl&gt;</code></pre>
<pre class="r"><code>cardio_data %&gt;% summarize_all(function(x) sum(is.na(x)))</code></pre>
<pre><code>## # A tibble: 1 x 16
## id age education sex is_smoking cigsPerDay BPMeds
prevalentStroke prevalentHyp diabetes
## &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt;
&lt;int&gt;
## 1 0 0 105 0 0 29 53 0 0 0
## # … with 6 more variables: chol &lt;int&gt;, sysBP &lt;int&gt;,
diaBP &lt;int&gt;, BMI &lt;int&gt;, heartRate &lt;int&gt;,
## # glucose &lt;int&gt;</code></pre>
<pre class="r"><code>cardio_data &lt;- cardio_data %&gt;% mutate(education = factor(education),
                                      BPMeds = factor(BPMeds),
                                      prevalentStroke = factor(prevalentStroke),
                                      prevalentHyp = factor(prevalentHyp),
                                      diabetes = factor(diabetes))
head(cardio_data)</code></pre>
<pre><code>## # A tibble: 6 x 16
## id age education sex is_smoking cigsPerDay BPMeds
prevalentStroke prevalentHyp diabetes
## &lt;dbl&gt; &lt;dbl&gt; &lt;fct&gt; &lt;chr&gt; &lt;chr&gt; &lt;dbl&gt; &lt;fct&gt; &lt;fct&gt; &lt;fct&gt;
&lt;fct&gt;
## 1 0 64 2 F YES 3 0 0 0 0
## 2 1 36 4 M NO 0 0 0 1 0
## 3 2 46 1 F YES 10 0 0 0 0
## 4 3 50 1 M YES 20 0 0 1 0
## 5 4 64 1 F YES 30 0 0 0 0
## 6 5 61 3 F NO 0 0 0 1 0
## # … with 6 more variables: chol &lt;chr&gt;, sysBP &lt;dbl&gt;,
diaBP &lt;dbl&gt;, BMI &lt;dbl&gt;, heartRate &lt;dbl&gt;,
## # glucose &lt;dbl&gt;</code></pre>
<p>The dataset contains several health and life statistics that contribute to cardiovascular health for different individuals. Each individual makes up and obervation and there are 4238 observations. There are 15 attributes for each of the variables and one ID column for each individual. Some common variables that contain health intake information includes the age, sex, and education level of the individual. Age is a numeric variable, sex is a binary variable, and education is a categorical variable that includes four different groups. For education, a 1 indicates some high school, a 2 is for a high school diploma or GED, a 3 indicates some college or vocational education, and a 4 is for a college graduate or higher. The is_smoking variable is a binary variable if the individual smokes and if so, how many cigarettes per day indicated by cigsPerDay. The BPMeds is a binary variable with 0 if the inidividual is not on blood pressure medications and a 1 if the individual is on blood pressure medications. Similar to BPMeds, prevalentStroke, prevalentHyp, and diabetes are all binary variables that tell whether the individual has had a stroke, is hypertensive, and is diabetic or not where 0 indicates no and 1 indicates yes. The chol variable is a categorical variable with three groups that indicates the total cholesterol level of the individual as good, borderline high, or high. The remaining variables include sysBP, diaBP, BMI, heartRate, and glucose which are all continuous numeric variables that measure systolic blood pressure, diastolic blood pressure, body mass index, heart rate, and glucose levels respectively.</p>
<ul>
<li><strong>1. (15 pts)</strong> Perform a MANOVA testing whether any of your numeric variables (or a subset of them, if including them all is unreasonable or doesn’t make sense) show a mean difference across levels of one of your categorical variables (3). If they do, perform univariate ANOVAs to find response(s) showing a mean difference across groups (3), and perform post-hoc t tests to find which groups differ (3). Discuss the number of tests you have performed, calculate the probability of at least one type I error (if unadjusted), and adjust the significance level accordingly (bonferroni correction) before discussing significant differences (3). Briefly discuss MANOVA assumptions and whether or not they are likely to have been met (no need for anything too in-depth) (2).</li>
</ul>
<pre class="r"><code># MANOVA and ANOVA
manova1 &lt;- manova(cbind(age, cigsPerDay, sysBP, diaBP, BMI, heartRate, glucose)~chol, data = cardio_data)
summary(manova1)</code></pre>
<pre><code>## Df Pillai approx F num Df den Df Pr(&gt;F)
## chol 2 0.093868 26.677 14 7584 &lt; 2.2e-16 ***
## Residuals 3797
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code>summary(aov(manova1))</code></pre>
<pre><code>## Response age :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## chol 2 20097 10048.7 146.79 &lt; 2.2e-16 ***
## Residuals 3797 259922 68.5
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Response cigsPerDay :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## chol 2 568 283.91 1.9964 0.136
## Residuals 3797 539983 142.21
##
## Response sysBP :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## chol 2 73062 36531 77.775 &lt; 2.2e-16 ***
## Residuals 3797 1783440 470
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Response diaBP :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## chol 2 14694 7347.1 52.703 &lt; 2.2e-16 ***
## Residuals 3797 529323 139.4
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Response BMI :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## chol 2 968 483.90 29.677 1.626e-13 ***
## Residuals 3797 61912 16.31
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Response heartRate :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## chol 2 3526 1763.02 12.469 4.004e-06 ***
## Residuals 3797 536864 141.39
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Response glucose :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## chol 2 2220 1109.92 1.9598 0.141
## Residuals 3797 2150366 566.33
##
## 438 observations deleted due to missingness</code></pre>
<pre class="r"><code># post-hoc t tests
pairwise.t.test(cardio_data$age, cardio_data$chol, p.adj = &quot;none&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  cardio_data$age and cardio_data$chol 
## 
##      borderline good  
## good &lt;2e-16     -     
## high &lt;2e-16     &lt;2e-16
## 
## P value adjustment method: none</code></pre>
<pre class="r"><code>pairwise.t.test(cardio_data$sysBP, cardio_data$chol, p.adj = &quot;none&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  cardio_data$sysBP and cardio_data$chol 
## 
##      borderline good   
## good 2.2e-09    -      
## high 3.3e-16    &lt; 2e-16
## 
## P value adjustment method: none</code></pre>
<pre class="r"><code>pairwise.t.test(cardio_data$diaBP, cardio_data$chol, p.adj = &quot;none&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  cardio_data$diaBP and cardio_data$chol 
## 
##      borderline good   
## good 4.5e-07    -      
## high 1.3e-11    &lt; 2e-16
## 
## P value adjustment method: none</code></pre>
<pre class="r"><code>pairwise.t.test(cardio_data$BMI, cardio_data$chol, p.adj = &quot;none&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  cardio_data$BMI and cardio_data$chol 
## 
##      borderline good   
## good 1.0e-06    -      
## high 0.00012    7.2e-15
## 
## P value adjustment method: none</code></pre>
<pre class="r"><code>pairwise.t.test(cardio_data$heartRate, cardio_data$chol, p.adj = &quot;none&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  cardio_data$heartRate and cardio_data$chol 
## 
##      borderline good   
## good 0.12543    -      
## high 0.00012    4.9e-06
## 
## P value adjustment method: none</code></pre>
<pre class="r"><code>1-0.95^23 # probability of a type 1 error</code></pre>
<pre><code>## [1] 0.6926431</code></pre>
<pre class="r"><code>0.05/23 # bonferroni adjusted significance</code></pre>
<pre><code>## [1] 0.002173913</code></pre>
<pre class="r"><code>group &lt;- cardio_data$chol
DVs &lt;- cardio_data %&gt;% select(age, cigsPerDay, sysBP, diaBP, BMI, heartRate, glucose)

# Test multivariate normality for each group (null: assumption met)
sapply(split(DVs, group), mshapiro_test)</code></pre>
<pre><code>##           borderline   good         high        
## statistic 0.6070601    0.6237763    0.6238191   
## p.value   6.232217e-52 1.980515e-37 1.199686e-47</code></pre>
<pre class="r"><code># If any p &lt; .05, stop. If not, test homogeneity of covariance matrices

#Box&#39;s M test (null: assumption met)
box_m(DVs, group)</code></pre>
<pre><code>## # A tibble: 1 x 4
## statistic p.value parameter method
## &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;
## 1 NA NA 56 Box&#39;s M-test for Homogeneity of Covariance
Matrices</code></pre>
<pre class="r"><code>#View covariance matrices for each group
lapply(split(DVs,group), cov)</code></pre>
<pre><code>## $borderline
## age cigsPerDay sysBP diaBP BMI heartRate glucose
## age 69.73795 NA 63.28633 17.08904 NA NA NA
## cigsPerDay NA NA NA NA NA NA NA
## sysBP 63.28633 NA 438.20120 194.26968 NA NA NA
## diaBP 17.08904 NA 194.26968 137.94020 NA NA NA
## BMI NA NA NA NA NA NA NA
## heartRate NA NA NA NA NA NA NA
## glucose NA NA NA NA NA NA NA
##
## $good
## age cigsPerDay sysBP diaBP BMI heartRate glucose
## age 68.772976 NA 70.19707 28.26892 NA 1.416163 NA
## cigsPerDay NA NA NA NA NA NA NA
## sysBP 70.197073 NA 399.82069 188.77610 NA 40.673904 NA
## diaBP 28.268922 NA 188.77610 139.76135 NA 25.733768 NA
## BMI NA NA NA NA NA NA NA
## heartRate 1.416163 NA 40.67390 25.73377 NA 153.291088 NA
## glucose NA NA NA NA NA NA NA
##
## $high
## age cigsPerDay sysBP diaBP BMI heartRate glucose
## age 65.722822 NA 62.80302 9.289682 NA -4.696605 NA
## cigsPerDay NA NA NA NA NA NA NA
## sysBP 62.803019 NA 540.94246 205.231712 NA 49.606605 NA
## diaBP 9.289682 NA 205.23171 136.280453 NA 26.881783 NA
## BMI NA NA NA NA NA NA NA
## heartRate -4.696605 NA 49.60661 26.881783 NA 145.807277
NA
## glucose NA NA NA NA NA NA NA</code></pre>
<p>The MANOVA performed indicates that at least one of the numeric variables in the data (age, cigsPerDay, sysBP, diaBP, BMI, heartRate, and glucose) show a mean difference across the levels of chol (p &lt; 2.2e-16) so univariate ANOVAs were done to find which dependent variables were different across the cholesterol groups. Based on the ANOVAs, five of the seven numeric variables were significant for differences between cholesterol groups so post-hoc t tests were performed for age, sysBP, diaBP, BMI, and heartRate to find which groups differed. There was 1 MANOVA, 7 ANOVAs, and 15 t-tests performed for a total of 23 hypothesis tests. Since there were a large number of tests performed, the probability of a type 1 error is 69.26% so in order to keep the error rate at 0.05, the bonferroni adjusted significance level should be 0.0022. The post hoc analysis was performed by conducting pairwise comparisons to determine which chol levels differed significantly for each of the five numeric variables mentioned previously. After adjusting for multiple compairsons (bonferroni ⍺ = 0.05/23 = 0.0022) all three levels of cholesterol differed significantly from each other in terms of age, sysBP, diaBP, BMI, and heartRate. After testing the multivariate normality for each group, the we reject the null and the assumption is not considered to be met becuase p &lt; 0.05.</p>
<ul>
<li><strong>2. (10 pts)</strong> Perform some kind of randomization test on your data (that makes sense). The statistic can be anything you want (mean difference, correlation, F-statistic/ANOVA, chi-squared), etc. State null and alternative hypotheses, perform the test, and interpret the results (7). Create a plot visualizing the null distribution and the test statistic (3).</li>
</ul>
<pre class="r"><code># calculating mean difference for glucose between prevalentHyp groups
mean(cardio_data %&gt;% filter(prevalentHyp == 1) %&gt;% pull(glucose), na.rm = T) - 
  mean(cardio_data %&gt;% filter(prevalentHyp == 0) %&gt;% pull(glucose), na.rm = T)</code></pre>
<pre><code>## [1] 4.487172</code></pre>
<pre class="r"><code>cardio_data %&gt;% group_by(prevalentHyp) %&gt;% summarize(means = mean(glucose, na.rm = T)) %&gt;% 
    summarize(diff(means))</code></pre>
<pre><code>## # A tibble: 1 x 1
##   `diff(means)`
##           &lt;dbl&gt;
## 1          4.49</code></pre>
<pre class="r"><code># parametric t test
cardio_log &lt;- cardio_data %&gt;% mutate(log_gluc = log(glucose))
t.test(data = cardio_log, log_gluc ~ prevalentHyp)</code></pre>
<pre><code>##
## Welch Two Sample t-test
##
## data: log_gluc by prevalentHyp
## t = -5.3681, df = 1944.1, p-value = 8.907e-08
## alternative hypothesis: true difference in means is not
equal to 0
## 95 percent confidence interval:
## -0.05628191 -0.02616203
## sample estimates:
## mean in group 0 mean in group 1
## 4.368093 4.409315</code></pre>
<pre class="r"><code>cardio_glucHyp &lt;- cardio_log %&gt;% na.omit() %&gt;% select(glucose, log_gluc, prevalentHyp)

# randomization test on log glucose values
rand_dist &lt;- vector()
for (i in 1:5000) {
    new &lt;- data.frame(log_gluc = sample(cardio_glucHyp$log_gluc), prevalentHyp = cardio_glucHyp$prevalentHyp)
    rand_dist[i] &lt;- mean(new[new$prevalentHyp == &quot;1&quot;,]$log_gluc) - mean(new[new$prevalentHyp == &quot;0&quot;, ]$log_gluc)
}
cardio_glucHyp %&gt;% group_by(prevalentHyp) %&gt;% summarize(means = mean(log_gluc)) %&gt;% 
    summarize(mean_diff = diff(means))</code></pre>
<pre><code>## # A tibble: 1 x 1
##   mean_diff
##       &lt;dbl&gt;
## 1    0.0418</code></pre>
<pre class="r"><code>mean(rand_dist &gt; 0.042 | rand_dist &lt; -0.042)</code></pre>
<pre><code>## [1] 0</code></pre>
<pre class="r"><code># randomization test on original glucose values
rand_dist &lt;- vector()
for (i in 1:5000) {
    new &lt;- data.frame(glucose = sample(cardio_glucHyp$glucose), prevalentHyp = cardio_glucHyp$prevalentHyp)
    rand_dist[i] &lt;- mean(new[new$prevalentHyp == &quot;1&quot;,]$glucose) - mean(new[new$prevalentHyp == &quot;0&quot;,]$glucose)
}
mean(rand_dist &gt; 4.487 | rand_dist &lt; -4.487)</code></pre>
<pre><code>## [1] 0</code></pre>
<pre class="r"><code>{hist(rand_dist, main = &quot;&quot;, ylab = &quot;&quot;, xlim = c(-4.5, 4.5)); abline(v = c(-4.487, 4.487), col = &quot;red&quot;)}</code></pre>
<p><img src="/project/project2_files/figure-html/unnamed-chunk-3-1.png" width="768" style="display: block; margin: auto;" />
The difference in glucose means between individuals that are not hypertensive and those that are hypertensive is 4.487. The parametric t-test gave a p-value of 8.907e-08 so you can reject the null hypothesis. The two groups, hypertensive or not do not have the same glucose levels on average. The two tailed p-values for the original glucose values and the log glucose values were both 0. The p-value of the parametric t-test is not 0 but the value is so small that these p-values are pretty much the same which leads to the same conclusion that the glucose levels of hypertensive and non-hypertensive individuals are different. A p-value of 0 from the randomization tests are common with large effects and this is evident by the histogram shown because there were no mean differences calculated from the randomization test outside the range of (-4.487, 4.487).</p>
<ul>
<li><p><strong>3. (35 pts)</strong> Build a linear regression model predicting one of your response variables from at least 2 other variables, including their interaction. Mean-center any numeric variables involved in the interaction.</p>
<ul>
<li>Interpret the coefficient estimates (do not discuss significance) (10)</li>
<li>Plot the regression using <code>ggplot()</code> using geom_smooth(method=“lm”). If your interaction is numeric by numeric, refer to code in the slides to make the plot or check out the <code>interactions</code> package, which makes this easier. If you have 3 or more predictors, just chose two of them to plot for convenience. (8)</li>
<li>Check assumptions of linearity, normality, and homoskedasticity either graphically or using a hypothesis test (4)</li>
<li>Regardless, recompute regression results with robust standard errors via <code>coeftest(..., vcov=vcovHC(...))</code>. Discuss significance of results, including any changes from before/after robust SEs if applicable. (8)</li>
<li>What proportion of the variation in the outcome does your model explain? (4)</li>
</ul></li>
</ul>
<pre class="r"><code># linear regression model 
cardio_data &lt;- cardio_data %&gt;% mutate(BMI_c = BMI - mean(BMI, na.rm = T))
fit &lt;- lm(glucose ~ BMI_c * chol, data = cardio_data)
summary(fit)</code></pre>
<pre><code>##
## Call:
## lm(formula = glucose ~ BMI_c * chol, data = cardio_data)
##
## Residuals:
## Min 1Q Median 3Q Max
## -46.637 -10.507 -3.643 4.816 314.890
##
## Coefficients:
## Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) 81.91952 0.57613 142.188 &lt;2e-16 ***
## BMI_c 0.36073 0.14343 2.515 0.0119 *
## cholgood -0.54531 1.05451 -0.517 0.6051
## cholhigh 0.54961 0.86093 0.638 0.5233
## BMI_c:cholgood 0.58118 0.24930 2.331 0.0198 *
## BMI_c:cholhigh 0.02845 0.21551 0.132 0.8950
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Residual standard error: 23.66 on 3820 degrees of
freedom
## (412 observations deleted due to missingness)
## Multiple R-squared: 0.009734, Adjusted R-squared:
0.008438
## F-statistic: 7.51 on 5 and 3820 DF, p-value: 5.024e-07</code></pre>
<pre class="r"><code># plotting the regression
cardio_na &lt;- cardio_data %&gt;% filter(!is.na(glucose)) %&gt;% filter(!is.na(BMI)) %&gt;% 
    filter(!is.na(chol))
mean_BMI &lt;- mean(cardio_data$BMI, na.rm = T)
cardio_na %&gt;% ggplot(aes(x = BMI, y = glucose, color = chol)) + 
  geom_point(aes(group = chol)) + geom_smooth(method = &quot;lm&quot;) + 
  geom_vline(xintercept = mean_BMI, linetype = &quot;dashed&quot;)</code></pre>
<p><img src="/project/project2_files/figure-html/unnamed-chunk-4-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>resids &lt;- fit$residuals
fitvals &lt;- fit$fitted.values
# plot to test for linearity
ggplot() + geom_point(aes(fitvals, resids)) + geom_hline(yintercept = 0, color = &quot;red&quot;)</code></pre>
<p><img src="/project/project2_files/figure-html/unnamed-chunk-4-2.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code># Breusch-Pagan (bp) for homoskedasticity
bptest(fit)</code></pre>
<pre><code>## 
##  studentized Breusch-Pagan test
## 
## data:  fit
## BP = 8.8008, df = 5, p-value = 0.1173</code></pre>
<pre class="r"><code># Shapiro-Wilk test for normality
shapiro.test(resids)</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  resids
## W = 0.57169, p-value &lt; 2.2e-16</code></pre>
<pre class="r"><code># recompute regression results with robust standard errors
summary(fit)$coef</code></pre>
<pre><code>## Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) 81.9195232 0.5761346 142.1881765 0.00000000
## BMI_c 0.3607287 0.1434314 2.5149921 0.01194424
## cholgood -0.5453115 1.0545139 -0.5171212 0.60510147
## cholhigh 0.5496065 0.8609339 0.6383841 0.52326195
## BMI_c:cholgood 0.5811828 0.2492960 2.3312963 0.01978949
## BMI_c:cholhigh 0.0284452 0.2155071 0.1319919 0.89499762</code></pre>
<pre class="r"><code>coeftest(fit, vcov = vcovHC(fit))</code></pre>
<pre><code>##
## t test of coefficients:
##
## Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) 81.919523 0.575142 142.4337 &lt; 2e-16 ***
## BMI_c 0.360729 0.163155 2.2110 0.02710 *
## cholgood -0.545312 1.080616 -0.5046 0.61385
## cholhigh 0.549607 0.878571 0.6256 0.53164
## BMI_c:cholgood 0.581183 0.335775 1.7309 0.08356 .
## BMI_c:cholhigh 0.028445 0.320216 0.0888 0.92922
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<p>The intercept is the mean/predicted glucose level, 81.92 mg/dL, for individuals with a borderline cholesterol and average BMI. The coefficient for BMI_c indicates that for every 1 unit increase in BMI there is a 0.361 mg/dL increase in glucose levels. The coefficient for cholgood indicates that individuals with good cholesterol and an average BMI have a predicted glucose level that is 0.5453 mg/dL lower than individuals with borderline cholesterol and cholhigh indicates that individuals with high cholesterol and an average BMI have a predicted glucose level that is 0.5496 mg/dL higher than individuals with a borderline cholesterol. The two interaction coefficients are BMI_c:cholgood and BMI_c:cholhigh. BMI_c:cholgood is 0.5812 so the slope of BMI on glucose for good cholesterol individuals is 0.5812 greater than for borderline cholesterol individuals. BMI_c:cholhigh is 0.0285 so the slope of BMI on glucose for high cholesterol individuals is 0.0285 greater than for borderline cholesterol individuals. Linearity was tested graphically and it is apparent that the assumption is not met because there is no random scattering of residuals but instead a strong clustering. Homoskedasticity and normality were tested using hypothesis tests. Based on the Breusch-Pagan (bp) test for homoskedasticity, the assumption was met because the p-value is 0.1173 so we fail to reject the null that the sample is homoskedastic. Based on the Shapiro-Wilk test for normality, the assumption was not met because the p-value &lt; 2.2e-16 so we reject the null hypothesis that the true distribution is normal. The regression was be redone to correct the standard errors which will decrease the t-values and increase the p-values so now p &gt; 0.05 for BMI_c:cholgood which is no longer significant in comparison to before using robust standard errors. The p-value of BMI_c increased from 0.0119 to 0.0271 but this is still a significant effect. Based on a R squared of 0.0097, 0.97% of variability in glucose is explained by the predictors.The adjusted R squared is even lower at 0.0084 becuase there is a penalty for each each extra explanatory variable used in the model.</p>
<ul>
<li><strong>4. (5 pts)</strong> Rerun same regression model (with the interaction), but this time compute bootstrapped standard errors (either by resampling observations or residuals). Discuss any changes you observe in SEs and p-values using these SEs compared to the original SEs and the robust SEs)</li>
</ul>
<pre class="r"><code>samp_distn &lt;- replicate(5000, {
    boot_dat &lt;- sample_frac(cardio_data, replace = T)
    fit &lt;- lm(glucose ~ BMI_c * chol, data = boot_dat)
    coef(fit) # save coefs
})
samp_distn %&gt;% t %&gt;% as.data.frame %&gt;% summarise_all(sd) # estimated SEs</code></pre>
<pre><code>## (Intercept) BMI_c cholgood cholhigh BMI_c:cholgood
BMI_c:cholhigh
## 1 0.5817886 0.1641429 1.08572 0.8747461 0.3235299
0.3204659</code></pre>
<p>After computing the bootstrapped standard errors by resampling observations, the standard errors found are slightly higher than the original standard errors but around the same or a little less than the robust standard errors for some coefficients. Since the assumption of heteroskedasicity was not violated, the all the standard errors were approximately the same and the p-values would also be similar. The null hypothesis for BMI_c can be rejected so there is a difference in glucose based on BMI_c based on this model.</p>
<ul>
<li><p><strong>5. (25 pts)</strong> Fit a logistic regression model predicting a binary variable (if you don’t have one, make/get one) from at least two explanatory variables (interaction not necessary).</p>
<ul>
<li>Interpret coefficient estimates in context (10)</li>
<li>Report a confusion matrix for your logistic regression (2)</li>
<li>Compute and discuss the Accuracy, Sensitivity (TPR), Specificity (TNR), Precision (PPV), and AUC of your model (5)</li>
<li>Using ggplot, make a density plot of the log-odds (logit) colored/grouped by your binary outcome variable (3)</li>
<li>Generate an ROC curve (plot) and calculate AUC (either manually or with a package); interpret (5)</li>
</ul></li>
</ul>
<pre class="r"><code># logistic model
cardio_dat &lt;- cardio_data %&gt;% mutate(is_smoking = ifelse(is_smoking == &quot;NO&quot;, 0, 1)) %&gt;% na.omit()
model &lt;- glm(is_smoking~sex+heartRate, data = cardio_dat, family = binomial(link=&quot;logit&quot;))
summary(model)</code></pre>
<pre><code>##
## Call:
## glm(formula = is_smoking ~ sex + heartRate, family =
binomial(link = &quot;logit&quot;),
## data = cardio_dat)
##
## Deviance Residuals:
## Min 1Q Median 3Q Max
## -1.6645 -1.0467 -0.9087 1.0661 1.5436
##
## Coefficients:
## Estimate Std. Error z value Pr(&gt;|z|)
## (Intercept) -1.435003 0.225988 -6.350 2.15e-10 ***
## sexM 0.886002 0.069003 12.840 &lt; 2e-16 ***
## heartRate 0.013171 0.002864 4.599 4.24e-06 ***
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## (Dispersion parameter for binomial family taken to be 1)
##
## Null deviance: 5066.5 on 3655 degrees of freedom
## Residual deviance: 4887.8 on 3653 degrees of freedom
## AIC: 4893.8
##
## Number of Fisher Scoring iterations: 4</code></pre>
<pre class="r"><code>prob &lt;- predict(model, type = &quot;response&quot;)
truth &lt;- cardio_dat$is_smoking
table(prediction = as.numeric(prob &gt; 0.5), truth) %&gt;% addmargins # confusion matrix</code></pre>
<pre><code>##           truth
## prediction    0    1  Sum
##        0   1207  790 1997
##        1    661  998 1659
##        Sum 1868 1788 3656</code></pre>
<pre class="r"><code>998/1659 # tnr </code></pre>
<pre><code>## [1] 0.6015672</code></pre>
<pre class="r"><code>1207/1997 # tpr</code></pre>
<pre><code>## [1] 0.6044066</code></pre>
<pre class="r"><code>1207/1868 # ppv</code></pre>
<pre><code>## [1] 0.6461456</code></pre>
<pre class="r"><code>(1207+998)/3656 # accuracy </code></pre>
<pre><code>## [1] 0.6031182</code></pre>
<pre class="r"><code># density plot
cardio_dat1 &lt;- cardio_data %&gt;% na.omit
cardio_dat1$logit &lt;- predict(model) # get predicted log-odds (logits)
cardio_dat1 %&gt;% mutate(is_smoking = factor(is_smoking, levels=c(&quot;YES&quot;, &quot;NO&quot;))) %&gt;% 
  ggplot(aes(logit, fill=is_smoking)) + geom_density(alpha = .3) +
  geom_vline(xintercept = 0, lty = 2)</code></pre>
<p><img src="/project/project2_files/figure-html/unnamed-chunk-6-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code># ROC plot
ROC_plot &lt;- ggplot(cardio_dat) + geom_roc(aes(d = is_smoking, m = prob), n.cuts = 0) + 
  geom_segment(aes(x = 0, xend = 1, y = 0, yend = 1), lty = 2)
ROC_plot</code></pre>
<p><img src="/project/project2_files/figure-html/unnamed-chunk-6-2.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>calc_auc(ROC_plot)</code></pre>
<pre><code>##   PANEL group       AUC
## 1     1    -1 0.6250861</code></pre>
<p>Controlling for heartRate, smoking in males and females is significantly different. The odds of smoking in males are e^0.886 = 2.425 times the odds of smoking in females. Controlling for sex, for every one unit increase in heartRate, the odds of smoking change by a factor of e^0.013 = 1.013 and this effect is also significant. Based on the confusion matrix, the true negative rate (specificity) is 0.6016, the true positive rate (sensitivity/recall) is 0.6044, the positive prediction value (precision) is 0.6461, and the overall accuracy is 0.6031. The AUC calculated from the ROC plot was 0.625 which is poor indicating that the prediction for is_smoking by the model is not that accurate.</p>
<ul>
<li><p><strong>6. (25 pts)</strong> Perform a logistic regression predicting the same binary response variable from <em>ALL</em> of the rest of your variables (the more, the better!)</p>
<ul>
<li>Fit model, compute in-sample classification diagnostics (Accuracy, Sensitivity, Specificity, Precision, AUC), and interpret (5)</li>
<li>Perform 10-fold (or repeated random sub-sampling) CV with the same model and report average out-of-sample classification diagnostics (Accuracy, Sensitivity, Specificity, Precision, and AUC); interpret AUC and compare with the in-sample metrics (10)</li>
<li>Perform LASSO on the same model/variables. Choose lambda to give the simplest model whose accuracy is near that of the best (i.e., <code>lambda.1se</code>). Discuss which variables are retained. (5)</li>
<li>Perform 10-fold CV using only the variables lasso selected: compare model’s out-of-sample AUC to that of your logistic regressions above (5)</li>
</ul></li>
</ul>
<pre class="r"><code>#HERE&#39;S THE CLASSIFICAITON DIAGNOSTICS FUNCTION
class_diag&lt;-function(probs,truth){
  tab&lt;-table(factor(probs&gt;.5,levels=c(&quot;FALSE&quot;,&quot;TRUE&quot;)),truth)
  acc=sum(diag(tab))/sum(tab)
  sens=tab[2,2]/colSums(tab)[2]
  spec=tab[1,1]/colSums(tab)[1]
  ppv=tab[2,2]/rowSums(tab)[2]
  f1=2*(sens*ppv)/(sens+ppv)

  if(is.numeric(truth)==FALSE &amp; is.logical(truth)==FALSE){
    truth&lt;-as.numeric(truth)-1}
  
  #CALCULATE EXACT AUC
  ord&lt;-order(probs, decreasing=TRUE)
  probs &lt;- probs[ord]; truth &lt;- truth[ord]
  
  TPR=cumsum(truth)/max(1,sum(truth)) 
  FPR=cumsum(!truth)/max(1,sum(!truth))
  
  dup&lt;-c(probs[-1]&gt;=probs[-length(probs)], FALSE)
  TPR&lt;-c(0,TPR[!dup],1); FPR&lt;-c(0,FPR[!dup],1)
  
  n &lt;- length(TPR)
  auc&lt;- sum( ((TPR[-1]+TPR[-n])/2) * (FPR[-1]-FPR[-n]) )

  data.frame(acc,sens,spec,ppv,f1,auc)
}</code></pre>
<pre class="r"><code># logistic model with all variables
cardio_mod &lt;- cardio_data %&gt;% select(-id, -cigsPerDay, -BMI_c) %&gt;%
  mutate(is_smoking = ifelse(is_smoking == &quot;NO&quot;, 0, 1)) %&gt;% na.omit()
model2 &lt;- glm(is_smoking~., data = cardio_mod, family = &quot;binomial&quot;)
summary(model2)</code></pre>
<pre><code>##
## Call:
## glm(formula = is_smoking ~ ., family = &quot;binomial&quot;, data
= cardio_mod)
##
## Deviance Residuals:
## Min 1Q Median 3Q Max
## -2.3894 -1.0548 -0.4907 1.0602 2.4649
##
## Coefficients:
## Estimate Std. Error z value Pr(&gt;|z|)
## (Intercept) 3.683339 0.497487 7.404 1.32e-13 ***
## age -0.048699 0.004861 -10.018 &lt; 2e-16 ***
## education2 0.056897 0.087047 0.654 0.51334
## education3 -0.095925 0.103678 -0.925 0.35485
## education4 -0.155009 0.118432 -1.309 0.19059
## sexM 1.044305 0.074722 13.976 &lt; 2e-16 ***
## BPMeds1 0.025033 0.230709 0.109 0.91360
## prevalentStroke1 -0.816231 0.557256 -1.465 0.14299
## prevalentHyp1 -0.002877 0.110095 -0.026 0.97915
## diabetes1 -0.052791 0.281050 -0.188 0.85101
## cholgood -0.070149 0.096816 -0.725 0.46872
## cholhigh 0.092762 0.080614 1.151 0.24986
## sysBP 0.004689 0.003154 1.487 0.13707
## diaBP -0.016794 0.005168 -3.249 0.00116 **
## BMI -0.082454 0.010221 -8.067 7.18e-16 ***
## heartRate 0.017994 0.003088 5.828 5.62e-09 ***
## glucose -0.002941 0.001954 -1.506 0.13216
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## (Dispersion parameter for binomial family taken to be 1)
##
## Null deviance: 5099.3 on 3678 degrees of freedom
## Residual deviance: 4630.0 on 3662 degrees of freedom
## AIC: 4664
##
## Number of Fisher Scoring iterations: 4</code></pre>
<pre class="r"><code>prob &lt;- predict(model2, type = &quot;response&quot;)
class_diag(prob, cardio_mod$is_smoking)</code></pre>
<pre><code>## acc sens spec ppv f1 auc
## 1 0.652623 0.6576477 0.6477516 0.644132 0.6508197
0.7024855</code></pre>
<pre class="r"><code># 10-fold CV
set.seed(2)
k = 10
data &lt;- cardio_mod %&gt;% sample_frac  # put rows of dataset in random order
folds &lt;- ntile(1:nrow(data), n = 10)  # create fold labels
diags &lt;- NULL
for (i in 1:k) {
    train &lt;- data[folds != i, ]  # create training set (all but fold i)
    test &lt;- data[folds == i, ]  # create test set (just fold i)
    truth &lt;- test$is_smoking  # save truth labels from fold i
    fit &lt;- glm(is_smoking ~ ., data = train, family = &quot;binomial&quot;)
    probs &lt;- predict(fit, newdata = test, type = &quot;response&quot;)
    diags &lt;- rbind(diags, class_diag(probs, truth))
}
summarise_all(diags, mean)</code></pre>
<pre><code>## acc sens spec ppv f1 auc
## 1 0.647464 0.6552467 0.6399354 0.6383397 0.6459764
0.6960615</code></pre>
<pre class="r"><code># LASSO
cardio_resp &lt;- as.matrix(cardio_mod$is_smoking)  # y 
cardio_preds &lt;- model.matrix(model2)[, -1]  # x
cardio_preds &lt;- scale(cardio_preds)

cv &lt;- cv.glmnet(cardio_preds, cardio_resp, family = &quot;binomial&quot;)
lasso_fit &lt;- glmnet(cardio_preds, cardio_resp, family = &quot;binomial&quot;, 
    lambda = cv$lambda.1se)
coef(lasso_fit)</code></pre>
<pre><code>## 17 x 1 sparse Matrix of class &quot;dgCMatrix&quot;
##                           s0
## (Intercept)      -0.03641049
## age              -0.30101349
## education2        .         
## education3        .         
## education4        .         
## sexM              0.35075826
## BPMeds1           .         
## prevalentStroke1  .         
## prevalentHyp1     .         
## diabetes1         .         
## cholgood          .         
## cholhigh          .         
## sysBP             .         
## diaBP            -0.02540740
## BMI              -0.22160653
## heartRate         0.07151066
## glucose           .</code></pre>
<pre class="r"><code># CV with LASSO selected variables
k = 10
cardio_mod1 &lt;- cardio_mod %&gt;% mutate(male = ifelse(cardio_mod == &quot;M&quot;, 1, 0))
data &lt;- cardio_mod1 %&gt;% sample_frac  # put rows of dataset in random order
folds &lt;- ntile(1:nrow(data), n = 10)  # create fold labels
diags &lt;- NULL
for (i in 1:k) {
    train &lt;- data[folds != i, ]  # create training set (all but fold i)
    test &lt;- data[folds == i, ]  # create test set (just fold i)
    truth &lt;- test$is_smoking  # save truth labels from fold i
    fit &lt;- glm(is_smoking ~ age + male + diaBP + BMI + heartRate, data = train, family = &quot;binomial&quot;)
    probs &lt;- predict(fit, newdata = test, type = &quot;response&quot;)
    diags &lt;- rbind(diags, class_diag(probs, truth))
}
summarise_all(diags, mean)</code></pre>
<pre><code>## acc sens spec ppv f1 auc
## 1 0.644466 0.6583233 0.632366 0.6347228 0.6455435
0.6976315</code></pre>
<p>After running the logistic regression with all the varibles excpet for id (irrelevant) and cigsPerDay (gives away the responce variable), the coefficients age, sex, diaBP, BMI, and heartRate all made a significant difference on the odds of smoking. The overall accuracy was 0.653, the sensitivity was 0.658, the specificity was 0.648, the positive prediction value was 0.644, and the AUC was 0.702. The AUC indicates that the model is fair. This indicates that the logistic model using almost all the variables avaliable was better at predicting is_smoking than just using sex and heartRate. After running a 10-fold CV, the average out-of-sample overall accurary was 0.647, sensitivity was 0.655, the specificity was 0.6399, the positive prediction vale was 0.638, and the AUC was 0.696. These out-of-sample classification diagnostics indicate that running a CV will give slightly less accurate prediction values in comparison to using the model in-sample which had better metrics. The variables retained after performing LASSO was age, sexM, diaBP, BMI, and heartRate. The CV using the non-zero variables found by LASSO has an accuracy of 0.644, a sensitivity of 0.658, a specificity of 0.632, a positive prediction value of 0.635, and an AUC of 0.698 which is borderline poor/fair. The out-of-sample AUC using the model from CV of LASSO variables is slightly worse than the original in-sample logistic regression of all the variables and about the same as the model with CV using all the variables.</p>
</div>
<div id="where-do-i-find-data-again" class="section level2">
<h2>Where do I find data again?</h2>
<p>You can choose ANY datasets you want that meet the above criteria for variables and observations. You can make it as serious as you want, or not, but keep in mind that you will be incorporating this project into a portfolio webpage for your final in this course, so choose something that really reflects who you are, or something that you feel will advance you in the direction you hope to move career-wise, or something that you think is really neat, or whatever. On the flip side, regardless of what you pick, you will be performing all the same tasks, so it doesn’t end up being that big of a deal.</p>
<p>If you are totally clueless and have no direction at all, log into the server and type</p>
<pre class="r"><code>data(package = .packages(all.available = TRUE))</code></pre>
<p>This will print out a list of <strong>ALL datasets in ALL packages</strong> installed on the server (a ton)! Scroll until your eyes bleed! Actually, do not scroll that much… To start with something more manageable, just run the command on your own computer, or just run <code>data()</code> to bring up the datasets in your current environment. To read more about a dataset, do <code>?packagename::datasetname</code>.</p>
<p>If it is easier for you, and in case you don’t have many packages installed, a list of R datasets from a few common packages (also downloadable in CSV format) is given at the following website: <a href="https://vincentarelbundock.github.io/Rdatasets/datasets.html" class="uri">https://vincentarelbundock.github.io/Rdatasets/datasets.html</a>.</p>
<ul>
<li><p>A good package to download for fun/relevant data is <code>fivethiryeight</code>.
Run <code>install.packages("fivethirtyeight"),</code> load the packages with <code>library(fivethirtyeight)</code>, run <code>data()</code>, and then scroll down to view the datasets. Here is an online list of all 127 datasets (with links to the 538 articles). Lots of sports, politics, current events, etc.</p></li>
<li><p>If you have already started to specialize (e.g., ecology, epidemiology) you might look at discipline-specific R packages (vegan, epi, respectively). We will be using some tools from these packages later in the course, but they come with lots of data too, which you can explore according to the directions above</p></li>
<li><p>However, you <em>emphatically DO NOT</em> have to use datasets available via R packages! In fact, I would much prefer it if you found the data from completely separate sources and brought them together (a much more realistic experience in the real world)! You can even reuse data from your SDS328M project, provided it shares a variable in common with other data which allows you to merge the two together (e.g., if you still had the timestamp, you could look up the weather that day: <a href="https://www.wunderground.com/history/" class="uri">https://www.wunderground.com/history/</a>). If you work in a research lab or have access to old data, you could potentially merge it with new data from your lab!</p></li>
<li><p>Here is a curated list of interesting datasets (read-only spreadsheet format): <a href="https://docs.google.com/spreadsheets/d/1wZhPLMCHKJvwOkP4juclhjFgqIY8fQFMemwKL2c64vk/edit" class="uri">https://docs.google.com/spreadsheets/d/1wZhPLMCHKJvwOkP4juclhjFgqIY8fQFMemwKL2c64vk/edit</a></p></li>
<li><p>Here is another great compilation of datasets: <a href="https://github.com/rfordatascience/tidytuesday" class="uri">https://github.com/rfordatascience/tidytuesday</a></p></li>
<li><p>Here is the UCI Machine Learning Repository: <a href="https://archive.ics.uci.edu/ml/index.php" class="uri">https://archive.ics.uci.edu/ml/index.php</a></p>
<ul>
<li>See also <a href="https://en.wikipedia.org/wiki/List_of_datasets_for_machine-learning_research#Biological_data" class="uri">https://en.wikipedia.org/wiki/List_of_datasets_for_machine-learning_research#Biological_data</a></li>
</ul></li>
<li><p>Here is another good general place to look: <a href="https://www.kaggle.com/datasets" class="uri">https://www.kaggle.com/datasets</a></p></li>
<li><p>To help narrow your search down or to see interesting variable ideas, check out <a href="https://www.tylervigen.com/spurious-correlations" class="uri">https://www.tylervigen.com/spurious-correlations</a>. This is the spurious correlations website, and it is fun, but if you look at the bottom of each plot you will see sources for the data. This is a good place to find very general data (or at least get a sense of where you can scrape data together from)!</p></li>
<li><p>If you are interested in medical data, check out www.countyhealthrankings.org</p></li>
<li><p>If you are interested in scraping UT data, they make <em>loads</em> of data public (e.g., beyond just professor CVs and syllabi). Check out all the data that is available in the statistical handbooks: <a href="https://reports.utexas.edu/statistical-handbook" class="uri">https://reports.utexas.edu/statistical-handbook</a></p></li>
</ul>
<div id="broader-data-sources" class="section level5">
<h5>Broader data sources:</h5>
<p><a href="www.data.gov">Data.gov</a> 186,000+ datasets!</p>
<p><a href="Social%20Explorer">Social Explorer</a> is a nice interface to Census and American Community Survey data (more user-friendly than the government sites). May need to sign up for a free trial.</p>
<p><a href="www.bls.gov">U.S. Bureau of Labor Statistics</a></p>
<p><a href="www.census.gov">U.S. Census Bureau</a></p>
<p><a href="www.gapminder.org/data">Gapminder</a>, data about the world.</p>
<p>…</p>
</div>
</div>
</div>

            
        <hr>         <div class="related-posts">
                <h5>Related Posts</h5>
                
              </div> 
            </div>
          </div>

   <hr>  <div class="disqus">
  <div id="disqus_thread"></div>
  <script type="text/javascript">

    (function() {
      
      
      if (window.location.hostname == "localhost")
        return;

      var disqus_shortname = '';
      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
  </script>
  <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
  <a href="http://disqus.com/" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
</div> 
        </div>
      </div>
    </div>

    
    <footer>
  <div id="footer">
    <div class="container">
      <p class="text-muted">&copy; All rights reserved. Powered by <a href="https://gohugo.io/">Hugo</a> and
      <a href="http://www.github.com/nurlansu/hugo-sustain/">sustain</a> with ♥</p>
    </div>
  </div>
</footer>
<div class="footer"></div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="/js/docs.min.js"></script>
<script src="/js/main.js"></script>

<script src="/js/ie10-viewport-bug-workaround.js"></script>


    
  </body>
</html>
